### PR TITLE
Add entity selection in config flow

### PR DESCRIPTION
**Pull request by rautesamtr**
Hey @IATkachenko what do you think of this approach for entity selection in the config flow?

### CODE REVIEW

**Comment by IATkachenko** [comment]
Like my solution it broke tests.
Also it creates confusing choise: user may select, for example, Co2 sensor as temperature. But now I have an idea how to fix issue 3 (missing) sensors in my version of this.
If you know how to fix tests, then I'll create PR (or send patch to this).

**Comment by rautesamtr** [comment]
I don't think we should restrict the selection of the the entities since not all support device_class attribute. e.g. command_line doesn't and helpers aren't sensors at all. Restricting the device class would not support such inputs in config flow and would force one to use yaml in such situation.
I understand that the selection may be confusing. In an ideal world we would offer an entry field with autocomplete suggestions. So far i haven't been able to achieve that with config flow. Any idea if that is possible?

**Comment by rautesamtr** [comment]
I'll look at the tests this evening.

**Comment by IATkachenko** [comment]
Could you have a look at #106? Based on my original idea I have added you clever solution with entities out of registry.

**Pull request closed without merging**
