### PR TITLE
avoid deprecated method call

### LINKED ISSUE #374: Warning since HA Update to 2024.5
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
Occurred for the first time: 07:58:32 (3 occurrences)
Last logged: 07:58:42

    Detected that custom integration 'thermal_comfort' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/thermal_comfort/__init__.py, line 162: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/dolezsa/thermal_comfort/issues
    Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
    Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

### LINKED ISSUE #376: hass.helpers.service deprecation
I just received the following WARNING in homeassistant.log:

2024-05-13 21:25:37.815 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'thermal_comfort' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/thermal_comfort/__init__.py, line 162: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/dolezsa/thermal_comfort/issues

Are you aware of that?

Thanks for the work anyhow. Just fell for it, as i noticed, how much of a value it added to my HAS.
Cheers,
Ag4m3mN0n

### PR DESCRIPTION
**Pull request by SukramJ**
Fixes #376
Fixes #374
Tested with HA 2024.5.3

### CODE REVIEW

**Comment by FabienD74** [comment]
UP!

**Comment by heinemannj** [comment]
Could somebody with write access approve and merge?

I'm ready for beta testing ...

**Comment by k8gg** [comment]
Would fix #370 also

**Comment by pejotigrek** [comment]
is it still waiting for merge?

**Pull request merged**
