### PR TITLE
Create sensor.pt.json (Portuguese Translation)

### PR DESCRIPTION
**Pull request by FragMenthor**

### CODE REVIEW

**Comment by FragMenthor** [comment]
Sorry to bother, but I wrote the initial translation. The translation does not appear in Portuguese, just the internal variables show (dry, very_confortable). Must we activate something so that this is available? Thanks in advance!

**Comment by IATkachenko** [comment]
@FragMenthor, hello.

For configuration steps translation you should use `pt.json` with translated values from `en.json`

**Comment by FragMenthor** [comment]
> @FragMenthor, hello.
> 
> For configuration steps translation you should use `pt.json` with translated values from `en.json`

I did, I created "sensor.pt.json" with translated text, created my first pull request, and it was added to main, and already published. But does not appear in HA... Missing something? Thanks for the help!

**Comment by rautesamtr** [comment]
image

Translation work fine here. Keep in mind translations only work in the frontend. #71

**Comment by IATkachenko** [comment]
Sorry for misunderstanding. `en.json` is only configuration steps strings, not for sensor data.
ps. don't forget clean browser cache.

**Comment by FragMenthor** [comment]
> Sorry for misunderstanding. `en.json` is only configuration steps strings, not for sensor data. ps. don't forget clean browser cache.

Thanks for your input, I think I finally understood what is happening: if I use it in a normal entities card, it's ok. I was using custom:multiple-entity-row with a custom secondary info, and that's probably why it's not working. Probably should report to the author of the multiple-entity-row  Thanks!!!
Screenshot_2022-01-24-22-04-30-164_io homeassistant companion android
Screenshot_2022-01-24-22-02-52-999_io homeassistant companion android

**Pull request merged**
