### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by kamahat**
In French translation, add entities names

### CODE REVIEW

**Comment by kamahat** [comment]
upto maintainer to commit

**Comment by rautesamtr** [comment]
Looks like you mixed in some tabs instead of spaces.
Also i just merged `Point de gelée` from @8mccm8 while your translation is `Point de gel`, which one is better?

**Comment by kamahat** [comment]
> Looks like you mixed in some tabs instead of spaces. Also i just merged `Point de gelée` from @8mccm8 while your translation is `Point de gel`, which one is better?

The good ones are "Point de Gel" or "Point de Givre", they are equivalent. We use "Point de Gelée Blanche" for ice made from a directe condensation of gaz water vapor to solid water.

**Comment by kamahat** [comment]
> Looks like you mixed in some tabs instead of spaces. 
Your right, the editor i've used did not make the difference...so my miskate.

**Comment by 8mccm8** [comment]
@rautesamtr  you can say both I think...

https://fr.wikipedia.org/wiki/Point_de_givrage

Le point de givrage, connu également comme la température du point givrage ou le point de gelée,

**Pull request closed without merging**
